notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - language: node_js
      node_js: lts/*
      install:
        - npm install
      script:
        - npm run test:unit
    - language: go
      go: 1.13.x
      git:
        depth: 1
      script:
        - go vet github.com/derat/mpticks/go/...
        - go test -v github.com/derat/mpticks/go/...
